- h1st/core/graph.py
- h1st/core/node.py
- tests/core/test_graph.py
- refactor node execution
- while executing, outputs of all executed nodes will be merged. If output of current node has common keys with merged result, values of those fields will be replaced by values from output of current node.
> enhance node execution

- examples/AutomotiveCybersecurity/models/blstm_injection_msg_classifier.py
- examples/AutomotiveCybersecurity/models/gradient_boosting_msg_classifier.py
- examples/AutomotiveCybersecurity/notebooks/Monolithic AD & ML Approaches and Why They are Unsatisfactory.ipynb
- examples/AutomotiveCybersecurity/notebooks/Using H1st.AI to Encode Human Insights as a Model and Harmonize Human + ML in a H1st.Graph.ipynb
- examples/Forecasting/models/forecast.py
- examples/Forecasting/notebooks/forecast.ipynb
- examples/HelloWorld/ml_model.py
- examples/HelloWorld/rule_based_model.py
- examples/HelloWorld/tests/test_hello_world.py
- h1st/cli/project.py
- h1st/core/model.py
- tests/core/test_ensemble_model.py
- tests/e2e/AutoCyberTutorial.ipynb
- tests/e2e/schema_sample/SchemaSample/models/SchemaSample.py
Verifying tests. Do not merge.
> Make Model methods concrete (vs. abstract)

- README.md
- examples/HelloWorld/README.md
- examples/HelloWorld/helloworld_graph.py
- examples/HelloWorld/ml_model.py
- examples/HelloWorld/rule_based_model.py
- examples/HelloWorld/tests/test_hello_world.py
- h1st/core/__init__.py
- h1st/core/node.py
HelloWorld graph does print `Hello World {x}!` for each even number `x` in the inputs. A test case is added.
Also update the ml_model.py to use persistence correctly.
Also update each example to be runnable script via `__main__`. README is added.
> Add HelloWorld graph example

- h1st/cli/project.py
- h1st/cli/templates/notebook.txt
- h1st/model_repository/model_repository.py
- tests/cli/test_cli.py
This PR replaces the initial project structure from modeling script to notebook as we now have notebook working correctly.
> replace modeling script with notebook

- h1st/core/__init__.py
- h1st/core/fuzzy_logic_model.py
- h1st/core/rule_based_model.py
- h1st/model_repository/model_repository.py
- h1st/requirements.txt
- tests/core/test_fuzzy_logic_model.py
Added fuzzy logic model into core. 
This FuzzyLogicModel allows users to encode rules in fuzzy way and solve small data problems.
> fuzzy logic model

- h1st/cli/project.py
- h1st/cli/templates/service.txt
> Model Serving Template

- h1st/tuner/hyperparameter_tuner.py
> Bugfix - use MLModel from h1st.core

- h1st/tuner/hyperparameter_tuner.py
> Bugfix - Add import h1st

- README.md
Fix graph example link on README
> Fix example link on README

- CODEOWNERS
> ci:adding codeowners

- examples/AIcargo/docker-compose.yml
> Revert "chore: enable AWS Cloudwatch driver for logging"

- .github/workflows/publish.yml
- .gitignore
- setup.py
> ci: github action to test publishing

- poetry.lock
- pyproject.toml
> chore: relax version requirement for scikit-learn

- docs/source/concepts/a1st.rst
- docs/source/concepts/ai-rule.rst
- docs/source/concepts/k1st.rst
- docs/source/concepts/object-model.rst
- docs/source/tutorials/quick-start/h1st-graph.rst.txt
- docs/source/tutorials/quick-start/installation.rst.txt
- docs/source/tutorials/quick-start/ml-model.rst.txt
- docs/source/tutorials/quick-start/oracle.rst.txt
- docs/source/tutorials/quick-start/rule-based-model.rst.txt
Grammar, phrasing and correctness edits to Concepts files.
Grammar, phrasing and example code updates to all Quick-start files EXCEPT Oracle
> Roshan docs edit

- .github/workflows/publish.yml
- pyproject.toml
References
* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-6
* https://github.com/marketplace/actions/manage-tags
> updating publish workflow to create github tag

- h1st/model/ensemble/classifier_stack_ensemble_modeler.py
- h1st/model/ensemble/ensemble.py
- h1st/model/ensemble/ensemble_modeler.py
- h1st/model/ensemble/stack_ensemble.py
- h1st/model/ensemble/stack_ensemble_modeler.py
- h1st/model/rule_based_model.py
- h1st/model/rule_based_modeler.py
- tests/model/test_stack_ensemble.py
> refactor: StackEnsemble with rule-based ensembler

- pyproject.toml
Changed the h1st version from 0.1.8 to 0.1.9
> updated version of h1st to 0.1.9

- tests/model/test_ts_oracle.py
fix:updated test_ts_oracle.py
- y value was randomly generated and sometimes only one class in y. 
- changed y to have more than 2 classes.
> fix:updated test_ts_oracle.py

- h1st/model/kswe/kswe_modeler.py
> fix: kswe to use self evaluate_model instead of submodel evaluate_model

- h1st/model/oracle/oracle.py
- h1st/model/oracle/oracle_modeler.py
- h1st/model/oracle/ts_oracle.py
- pyproject.toml
- setup.cfg
- tests/model/test_oracle.py
- tests/model/test_ts_oracle.py
Refactor oracle to instantiate without having to pass teacher, students and ensembler. Allowing simple load/persist behavior. 
- Include unit tests. If small test files are needed for your unit tests, please include them as well. Be conservative in adding test files, try …
> Oracle load patch

- docs/source/tutorials/quick-start/installation.rst.txt
updated the installation instructions to avoid incompatible issues when using Python 3.10
- Include unit tests. If small test files are needed for your unit tests, please include them as well. Be conservative in adding test files, try to make them small and local instead …
> doc: Update installation.rst.txt

- .github/workflows/test.yml
- h1st/model/oracle/oracle.py
This PR implemented a better CI pipeline with a test matrix including:
- All supported Python version: 3.8, 3.9 and 3.10
- All supported OS: Linux, Mac, Windows
- ARM architecture on Linux
Here is a new sample CI run: https://github.com/h1st-ai/h1st/actions/runs/3234879223/jobs/5298542835
> Better CI pipeline with test matrix including all supported Python version and all supported OS

- h1st/model/ml/xgboost/classifier.py
- h1st/model/ml/xgboost/regression.py
- pyproject.toml
- setup.cfg
> fix: remove Model as suffix in XGB model name, update version to 2.1.1

- pyproject.toml
> fix: use ~ in pyproject instead of >=
